package org.community.common.user;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum UserResponseMessage {
    // 회원가입 관련
    SIGNUP_SUCCESS(201, "SIGNUP_SUCCESS"),
    INVALID_INFO(400, "INVALID_INFO"), // 이메일, 닉네임, 패스워드 형식 오류
    DUPLICATE_EMAIL(409, "DUPLICATE_EMAIL"), // 이메일 중복
    DUPLICATE_NICKNAME(409, "DUPLICATE_NICKNAME"),

    // 로그인 관련
    LOGIN_SUCCESS(200, "LOGIN_SUCCESS"),
    INVALID_EMAIL(400, "INVALID_EMAIL"), // 로그인 실패
    INVALID_PASSWORD(400, "INVALID_PASSWORD"),

    // 회원 관련
    UPDATE_SUCCESS(204, "UPDATE_SUCCESS"),
    DELETE_SUCCESS(204, "DELETE_SUCCESS" ),
    USER_NOT_FOUND(404, "USER_NOT_FOUND"),
    USER_FETCH_SUCCESS(200, "USER_FETCH_SUCCESS"),
    NOT_DUPLICATE_NICKNAME(204, "NOT_DUPLICATE_NICKNAME"),

    //JWT 관련
    JWT_CREATION_SUCCESS(200, "JWT_CREATION_SUCCESS"), // JWT 생성 성공
    JWT_EXPIRED(401, "JWT_EXPIRED"), // JWT 만료됨
    JWT_INVALID(401, "JWT_INVALID"), // JWT가 유효하지 않음
    JWT_UNSUPPORTED(401, "JWT_UNSUPPORTED"), // 지원하지 않는 JWT 형식
    JWT_MISSING(401, "JWT_MISSING"), // 요청 헤더에 JWT 없음
    JWT_VERIFICATION_FAILED(403, "JWT_VERIFICATION_FAILED"), // JWT 검증 실패

    //Post 관련
    POST_FETCH_SUCCESS(200, "POST_FETCH_SUCCESS"),
    POST_CREATED(201, "POST_CREATED"),
    POST_NOT_FOUND(404, "POST_NOT_FOUND"),
    POST_UPDATED(204, "POST_UPDATED"),
    POST_DELETED(204, "POST_DELETED"),
    POST_VIEWED(204, "POST_VIEWED"),

    //Comment 관련
    COMMENT_CREATED(204, "COMMENT_CREATED"),
    COMMENT_FETCH_SUCCESS(200, "COMMENT_FETCH_SUCCESS"),
    COMMENT_NOT_FOUND(404, "COMMENT_NOT_FOUND"),
    COMMENT_UPDATED(204, "COMMENT_UPDATED"),
    COMMENT_DELETED(204, "COMMENT_DELETED"),

    //Like 관련
    LIKE_FETCH_SUCCESS(200, "LIKE_FETCH_SUCCESS"),
    LIKE_ADDED(204, "LIKE_ADDED"),
    LIKE_DELETED(204, "LIKE_DELETED");

    private final int statusCode;
    private final String message;
}
